name = "launch-mom-app"
main = "src/index.ts"
compatibility_date = "2025-01-04"

[vars]
GITHUB_CLIENT_ID = "Ov23li3zEh41OeusUfbi"
GITHUB_CLIENT_SECRET = "fde3642bcba3c22ec5e58c317fc53e219246afa7"
GOOGLE_SHEETS_API_KEY = "AIzaSyAS67sfMCMSGr-k3zfoY5hGO135qBczz3E"
GOOGLE_SPREADSHEET_ID = "1jbgh1vryuksoXnRBJ-vcdbD3W_ncaf3CNc4N5HRPAng"


# compatibility_flags = [ "nodejs_compat" ]


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1